# Generated by Django 4.1.4 on 2022-12-22 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VidStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=600)),
                ('playlist', models.TextField(max_length=600)),
                ('upload_date', models.DateField(default=django.utils.timezone.now)),
                ('video', models.FileField(upload_to='')),
            ],
        ),
    ]
