# Generated by Django 4.1.4 on 2022-12-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vidstream',
            name='author_email',
            field=models.EmailField(blank=True, max_length=30),
        ),
    ]
